# Copyright (c) 2022, Atrina Technologies Pvt Ltd and contributors
# For license information, please see license.txt

import frappe
from frappe.model.document import Document

class SecondaryCustomerForm(Document):
	def on_update(self):
		try:
			print("\n\n\nI am from customer form\n\n\n")
			# print("The self.name is \n\n",self.name)
			asm_rsm = [x for x in frappe.db.sql("""select shm.asm_user,shm.rsm_user from `tabSecondary Customer Form` cf inner join `tabSales Hierarchy Mapping` shm on shm.asm_user = cf.asm_user where cf.name = '{}'""".format(self.name), as_list=1)]
			asm_rsm_name = [x for x in frappe.db.sql("""select shm.asm_name,shm.rsm_name from `tabSecondary Customer Form` cf inner join `tabSales Hierarchy Mapping` shm on shm.asm_user = cf.asm_user where cf.name = '{}'""".format(self.name), as_list=1)]
			nsm_user = [x for x in frappe.db.sql("""select shm.nsm_user from `tabSecondary Customer Form` cf inner join `tabSales Hierarchy Mapping` shm on shm.asm_user = cf.asm_user where cf.name = '{}'""".format(self.name), as_list=1)]
			nsm_name = [x for x in frappe.db.sql("""select shm.nsm_name from `tabSecondary Customer Form` cf inner join `tabSales Hierarchy Mapping` shm on shm.asm_user = cf.asm_user where cf.name = '{}'""".format(self.name), as_list=1)]
			scma_list =[x[0] for x in frappe.db.sql("""select u.name from `tabUser` u inner join `tabHas Role` hr on hr.parent = u.name where hr.role = 'Secondary Customer Master Approver'""", as_list=1)]
			scma_name =[x[0] for x in frappe.db.sql("""select u.full_name from `tabUser` u inner join `tabHas Role` hr on hr.parent = u.name where hr.role = 'Secondary Customer Master Approver'""", as_list=1)]
			rtm_list =[x[0] for x in frappe.db.sql("""select u.name from `tabUser` u inner join `tabHas Role` hr on hr.parent = u.name where hr.role = 'RTM Manager'""", as_list=1)]

			print("The asm is ",asm_rsm[0][0])
			print("The rsm is ",asm_rsm[0][1])
			print("The scma is ",scma_list)


			if self.workflow_state == 'Pending for NSM Approval':
				frappe.db.set_value("Secondary Customer Form", self.name, "secondary_customer_additional_details_approval_time", frappe.utils.now())
				msg="""Hello {},<br><br>
				You have received a request for Secondary customer creation approval from {} for the customer {}.<br><br>
				Kindly login to apps.myhector.com for the approval process.<br><br><br>
				Regards,<br>
				Hector Beverages
				<br><br><p style="color:#424242;font-size:12px">In connection with your association with the company as a customer, you may provide to the company, certain information with respect to entity identification details, registration numbers, PAN and/or GST numbers, bank account details, personal information including sensitive personal data or information (as such term is defined in the Information Technology Act, 2000 read with the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011) and the Aadhaar number (as such term is defined under the Aadhaar (Targeted Delivery of Financial and Other Subsidies, Benefits and Services) Act, 2016), as may be applicable (“Information”). Any Information, if shared by you with the company, will be shared by you having full legal capacity and authority to share such Information and such Information will be collected, processed, stored, handled, used, transferred, disclosed and/or retained, as may be required, in accordance with the company’s confidentiality obligations, privacy policy and subject to applicable law, for the purpose of administering your association with the company and based on the requirements of such association for onboarding, registration, billing, accounting, conducting background checks, in connection with business of the company and the company’s internal record keeping purposes. The company may either by itself, or through third party service providers, process any Information for relevant and limited purposes in connection with your association with the company, subject to applicable laws. You, having read and understood the aforesaid terms of collection, processing, handling, use, transfer and disclosure of Information, are requested to provide your express consent while sharing the Information with the company. You shall as and when there is any update to the Information shared with the company, seek access and update such Information which relates to you. Your sharing of the Information with the company shall certify that such Information provided by you to the company is true, accurate and complete, and you hereby agree to fully indemnify and keep indemnified the company, its management, employees and representatives for any claims, demands, losses, damages, actions and/or other liabilities, whether financial or otherwise, arising directly or indirectly from any reliance upon such Information.</p>""".format(nsm_name[0][0],asm_rsm_name[0][0],self.name_of_new_distributor)
				frappe.sendmail(subject="Customer Creation: Pending for NSM Approval", content=msg, recipients = '{}'.format(nsm_user[0][0]),sender="Notification@hectorbeverages.com")
				print("\n email sent \n")

			if self.workflow_state == 'Pending For Secondary Customer Additional Details':
				msg="""Hello {},<br><br>
				You have received a request to fill Secondary Customer Additional Details for the customer {}.<br><br>
				Kindly login to apps.myhector.com for the approval process.<br><br><br>
				Regards,<br>
				Hector Beverages
				<br><br><p style="color:#424242;font-size:12px">In connection with your association with the company as a customer, you may provide to the company, certain information with respect to entity identification details, registration numbers, PAN and/or GST numbers, bank account details, personal information including sensitive personal data or information (as such term is defined in the Information Technology Act, 2000 read with the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011) and the Aadhaar number (as such term is defined under the Aadhaar (Targeted Delivery of Financial and Other Subsidies, Benefits and Services) Act, 2016), as may be applicable (“Information”). Any Information, if shared by you with the company, will be shared by you having full legal capacity and authority to share such Information and such Information will be collected, processed, stored, handled, used, transferred, disclosed and/or retained, as may be required, in accordance with the company’s confidentiality obligations, privacy policy and subject to applicable law, for the purpose of administering your association with the company and based on the requirements of such association for onboarding, registration, billing, accounting, conducting background checks, in connection with business of the company and the company’s internal record keeping purposes. The company may either by itself, or through third party service providers, process any Information for relevant and limited purposes in connection with your association with the company, subject to applicable laws. You, having read and understood the aforesaid terms of collection, processing, handling, use, transfer and disclosure of Information, are requested to provide your express consent while sharing the Information with the company. You shall as and when there is any update to the Information shared with the company, seek access and update such Information which relates to you. Your sharing of the Information with the company shall certify that such Information provided by you to the company is true, accurate and complete, and you hereby agree to fully indemnify and keep indemnified the company, its management, employees and representatives for any claims, demands, losses, damages, actions and/or other liabilities, whether financial or otherwise, arising directly or indirectly from any reliance upon such Information.</p>""".format(asm_rsm_name[0][0],self.name_of_new_distributor)
				frappe.sendmail(subject="Customer Creation: Pending For Secondary Customer Additional Details", content=msg, recipients = '{}'.format(asm_rsm[0][0]), sender="Notification@hectorbeverages.com")
				print("\n email sent \n")

			if self.workflow_state == 'Resent for NSM Approval':
				frappe.db.set_value("Secondary Customer Form", self.name, "resent_for_nsm_approval_time", frappe.utils.now())
				msg="""Hello {},<br><br>
				You have received a request for Secondary customer creation approval from {} for the customer {}.<br><br>
				Kindly login to apps.myhector.com for the approval process.<br><br><br>
				Regards,<br>
				Hector Beverages
				<br><br><p style="color:#424242;font-size:12px">In connection with your association with the company as a customer, you may provide to the company, certain information with respect to entity identification details, registration numbers, PAN and/or GST numbers, bank account details, personal information including sensitive personal data or information (as such term is defined in the Information Technology Act, 2000 read with the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011) and the Aadhaar number (as such term is defined under the Aadhaar (Targeted Delivery of Financial and Other Subsidies, Benefits and Services) Act, 2016), as may be applicable (“Information”). Any Information, if shared by you with the company, will be shared by you having full legal capacity and authority to share such Information and such Information will be collected, processed, stored, handled, used, transferred, disclosed and/or retained, as may be required, in accordance with the company’s confidentiality obligations, privacy policy and subject to applicable law, for the purpose of administering your association with the company and based on the requirements of such association for onboarding, registration, billing, accounting, conducting background checks, in connection with business of the company and the company’s internal record keeping purposes. The company may either by itself, or through third party service providers, process any Information for relevant and limited purposes in connection with your association with the company, subject to applicable laws. You, having read and understood the aforesaid terms of collection, processing, handling, use, transfer and disclosure of Information, are requested to provide your express consent while sharing the Information with the company. You shall as and when there is any update to the Information shared with the company, seek access and update such Information which relates to you. Your sharing of the Information with the company shall certify that such Information provided by you to the company is true, accurate and complete, and you hereby agree to fully indemnify and keep indemnified the company, its management, employees and representatives for any claims, demands, losses, damages, actions and/or other liabilities, whether financial or otherwise, arising directly or indirectly from any reliance upon such Information.</p>""".format(nsm_name[0][0],asm_rsm_name[0][0],self.name_of_new_distributor)
				frappe.sendmail(subject="Customer Creation: Resent for NSM Approval", content=msg, recipients = '{}'.format(nsm_user[0][0]),sender="Notification@hectorbeverages.com")
				print("\n email sent \n")

			if self.workflow_state == 'Pending with Secondary Master Processing':
				frappe.db.set_value("Secondary Customer Form", self.name, "rtm_approval_time", frappe.utils.now())
				for i in range(len(scma_list)):
					msg="""Hello {},<br><br>
					You have received a request for Secondary customer creation from RTM Manager for the customer {}.<br><br>
					Kindly login to apps.myhector.com for the approval process.<br><br><br>
					Regards,<br>
					Hector Beverages
					<br><br><p style="color:#424242;font-size:12px">In connection with your association with the company as a customer, you may provide to the company, certain information with respect to entity identification details, registration numbers, PAN and/or GST numbers, bank account details, personal information including sensitive personal data or information (as such term is defined in the Information Technology Act, 2000 read with the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011) and the Aadhaar number (as such term is defined under the Aadhaar (Targeted Delivery of Financial and Other Subsidies, Benefits and Services) Act, 2016), as may be applicable (“Information”). Any Information, if shared by you with the company, will be shared by you having full legal capacity and authority to share such Information and such Information will be collected, processed, stored, handled, used, transferred, disclosed and/or retained, as may be required, in accordance with the company’s confidentiality obligations, privacy policy and subject to applicable law, for the purpose of administering your association with the company and based on the requirements of such association for onboarding, registration, billing, accounting, conducting background checks, in connection with business of the company and the company’s internal record keeping purposes. The company may either by itself, or through third party service providers, process any Information for relevant and limited purposes in connection with your association with the company, subject to applicable laws. You, having read and understood the aforesaid terms of collection, processing, handling, use, transfer and disclosure of Information, are requested to provide your express consent while sharing the Information with the company. You shall as and when there is any update to the Information shared with the company, seek access and update such Information which relates to you. Your sharing of the Information with the company shall certify that such Information provided by you to the company is true, accurate and complete, and you hereby agree to fully indemnify and keep indemnified the company, its management, employees and representatives for any claims, demands, losses, damages, actions and/or other liabilities, whether financial or otherwise, arising directly or indirectly from any reliance upon such Information.</p>""".format(frappe.get_doc('User', scma_list[i]).full_name,self.name_of_new_distributor)
					frappe.sendmail(subject="Customer Creation: Pending with Secondary Master Processing", content=msg, recipients = '{}'.format(scma_list[i]), sender="Notification@hectorbeverages.com")
					print("\n email sent \n")

			if self.workflow_state == 'Resent for Secondary Master Processing':
				frappe.db.set_value("Secondary Customer Form", self.name, "resent_for_secondary_master_processing_time", frappe.utils.now())
				for i in range(len(scma_list)):
					msg="""Hello {},<br><br>
					You have received a request for Secondary customer creation from {} for the customer {}.<br><br>
					Kindly login to apps.myhector.com for the approval process.<br><br><br>
					Regards,<br>
					Hector Beverages
					<br><br><p style="color:#424242;font-size:12px">In connection with your association with the company as a customer, you may provide to the company, certain information with respect to entity identification details, registration numbers, PAN and/or GST numbers, bank account details, personal information including sensitive personal data or information (as such term is defined in the Information Technology Act, 2000 read with the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011) and the Aadhaar number (as such term is defined under the Aadhaar (Targeted Delivery of Financial and Other Subsidies, Benefits and Services) Act, 2016), as may be applicable (“Information”). Any Information, if shared by you with the company, will be shared by you having full legal capacity and authority to share such Information and such Information will be collected, processed, stored, handled, used, transferred, disclosed and/or retained, as may be required, in accordance with the company’s confidentiality obligations, privacy policy and subject to applicable law, for the purpose of administering your association with the company and based on the requirements of such association for onboarding, registration, billing, accounting, conducting background checks, in connection with business of the company and the company’s internal record keeping purposes. The company may either by itself, or through third party service providers, process any Information for relevant and limited purposes in connection with your association with the company, subject to applicable laws. You, having read and understood the aforesaid terms of collection, processing, handling, use, transfer and disclosure of Information, are requested to provide your express consent while sharing the Information with the company. You shall as and when there is any update to the Information shared with the company, seek access and update such Information which relates to you. Your sharing of the Information with the company shall certify that such Information provided by you to the company is true, accurate and complete, and you hereby agree to fully indemnify and keep indemnified the company, its management, employees and representatives for any claims, demands, losses, damages, actions and/or other liabilities, whether financial or otherwise, arising directly or indirectly from any reliance upon such Information.</p>""".format(frappe.get_doc('User', scma_list[i]).full_name,nsm_name[0][0],self.name_of_new_distributor)
					frappe.sendmail(subject="Customer Creation: Resent for Secondary Master Processing", content=msg, recipients = '{}'.format(scma_list[i]), sender="Notification@hectorbeverages.com")
					print("\n email sent \n")


			if self.workflow_state == 'Requested for More Details by NSM':
				frappe.db.set_value("Secondary Customer Form", self.name, "requested_for_more_details_by_nsm_time", frappe.utils.now())
				msg="""Hello {},<br><br>
				You have received a request for more information in Secondary customer creation from {} for the customer {}.<br><br>
				Kindly login to apps.myhector.com for the approval process.<br><br><br>
				Regards,<br>
				Hector Beverages
				<br><br><p style="color:#424242;font-size:12px">In connection with your association with the company as a customer, you may provide to the company, certain information with respect to entity identification details, registration numbers, PAN and/or GST numbers, bank account details, personal information including sensitive personal data or information (as such term is defined in the Information Technology Act, 2000 read with the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011) and the Aadhaar number (as such term is defined under the Aadhaar (Targeted Delivery of Financial and Other Subsidies, Benefits and Services) Act, 2016), as may be applicable (“Information”). Any Information, if shared by you with the company, will be shared by you having full legal capacity and authority to share such Information and such Information will be collected, processed, stored, handled, used, transferred, disclosed and/or retained, as may be required, in accordance with the company’s confidentiality obligations, privacy policy and subject to applicable law, for the purpose of administering your association with the company and based on the requirements of such association for onboarding, registration, billing, accounting, conducting background checks, in connection with business of the company and the company’s internal record keeping purposes. The company may either by itself, or through third party service providers, process any Information for relevant and limited purposes in connection with your association with the company, subject to applicable laws. You, having read and understood the aforesaid terms of collection, processing, handling, use, transfer and disclosure of Information, are requested to provide your express consent while sharing the Information with the company. You shall as and when there is any update to the Information shared with the company, seek access and update such Information which relates to you. Your sharing of the Information with the company shall certify that such Information provided by you to the company is true, accurate and complete, and you hereby agree to fully indemnify and keep indemnified the company, its management, employees and representatives for any claims, demands, losses, damages, actions and/or other liabilities, whether financial or otherwise, arising directly or indirectly from any reliance upon such Information.</p>""".format(asm_rsm_name[0][0],nsm_name[0][0],self.name_of_new_distributor)
				frappe.sendmail(subject="Customer Creation: Requested for More Details by NSM", content=msg, recipients = '{}'.format(asm_rsm[0][0]), sender="Notification@hectorbeverages.com")
				print("\n email sent \n")

			if self.workflow_state == 'Requested for More Details by Secondary Master Team':
				frappe.db.set_value("Secondary Customer Form", self.name, "requested_for_more_details_by_secondary_master_team_time", frappe.utils.now())
				msg="""Hello {},<br><br>
				You have received a request for more information in Secondary customer creation from {} for the customer {}.<br><br>
				Kindly login to apps.myhector.com for the approval process.<br><br><br>
				Regards,<br>
				Hector Beverages
				<br><br><p style="color:#424242;font-size:12px">In connection with your association with the company as a customer, you may provide to the company, certain information with respect to entity identification details, registration numbers, PAN and/or GST numbers, bank account details, personal information including sensitive personal data or information (as such term is defined in the Information Technology Act, 2000 read with the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011) and the Aadhaar number (as such term is defined under the Aadhaar (Targeted Delivery of Financial and Other Subsidies, Benefits and Services) Act, 2016), as may be applicable (“Information”). Any Information, if shared by you with the company, will be shared by you having full legal capacity and authority to share such Information and such Information will be collected, processed, stored, handled, used, transferred, disclosed and/or retained, as may be required, in accordance with the company’s confidentiality obligations, privacy policy and subject to applicable law, for the purpose of administering your association with the company and based on the requirements of such association for onboarding, registration, billing, accounting, conducting background checks, in connection with business of the company and the company’s internal record keeping purposes. The company may either by itself, or through third party service providers, process any Information for relevant and limited purposes in connection with your association with the company, subject to applicable laws. You, having read and understood the aforesaid terms of collection, processing, handling, use, transfer and disclosure of Information, are requested to provide your express consent while sharing the Information with the company. You shall as and when there is any update to the Information shared with the company, seek access and update such Information which relates to you. Your sharing of the Information with the company shall certify that such Information provided by you to the company is true, accurate and complete, and you hereby agree to fully indemnify and keep indemnified the company, its management, employees and representatives for any claims, demands, losses, damages, actions and/or other liabilities, whether financial or otherwise, arising directly or indirectly from any reliance upon such Information.</p>""".format(asm_rsm_name[0][0],scma_name[0],self.name_of_new_distributor)
				frappe.sendmail(subject="Customer Creation: Requested for More Details by Secondary Master Data Team", content=msg, recipients = '{}'.format(asm_rsm[0][0]), sender="Notification@hectorbeverages.com")
				print("\n email sent \n")

			if self.workflow_state == 'Rejected by NSM':
				frappe.db.set_value("Secondary Customer Form", self.name, "rejected_by_nsm_time", frappe.utils.now())
				msg="""Hello {},<br><br>
				Your request for Secondary customer creation for customer {} has been rejected by {}.<br><br>
				Kindly check reason for rejection in website apps.myhector.com<br><br><br>
				Regards,<br>
				Hector Beverages
				<br><br><p style="color:#424242;font-size:12px">In connection with your association with the company as a customer, you may provide to the company, certain information with respect to entity identification details, registration numbers, PAN and/or GST numbers, bank account details, personal information including sensitive personal data or information (as such term is defined in the Information Technology Act, 2000 read with the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011) and the Aadhaar number (as such term is defined under the Aadhaar (Targeted Delivery of Financial and Other Subsidies, Benefits and Services) Act, 2016), as may be applicable (“Information”). Any Information, if shared by you with the company, will be shared by you having full legal capacity and authority to share such Information and such Information will be collected, processed, stored, handled, used, transferred, disclosed and/or retained, as may be required, in accordance with the company’s confidentiality obligations, privacy policy and subject to applicable law, for the purpose of administering your association with the company and based on the requirements of such association for onboarding, registration, billing, accounting, conducting background checks, in connection with business of the company and the company’s internal record keeping purposes. The company may either by itself, or through third party service providers, process any Information for relevant and limited purposes in connection with your association with the company, subject to applicable laws. You, having read and understood the aforesaid terms of collection, processing, handling, use, transfer and disclosure of Information, are requested to provide your express consent while sharing the Information with the company. You shall as and when there is any update to the Information shared with the company, seek access and update such Information which relates to you. Your sharing of the Information with the company shall certify that such Information provided by you to the company is true, accurate and complete, and you hereby agree to fully indemnify and keep indemnified the company, its management, employees and representatives for any claims, demands, losses, damages, actions and/or other liabilities, whether financial or otherwise, arising directly or indirectly from any reliance upon such Information.</p>""".format(asm_rsm_name[0][0],self.name_of_new_distributor,nsm_name[0][0])
				frappe.sendmail(subject="Customer Creation Rejected : {}".format(self.name_of_new_distributor), content=msg, recipients = '{}'.format(asm_rsm[0][0]), sender="Notification@hectorbeverages.com")
				print("\n email sent \n")

			if self.workflow_state == 'Rejected by ASM':
				frappe.db.set_value("Secondary Customer Form", self.name, "rejected_by_asm_time", frappe.utils.now())
				msg="""Hello,<br><br>
				Your request for Secondary customer creation for customer {} has been rejected by {}.<br><br>
				Kindly check reason for rejection in website apps.myhector.com<br><br><br>
				Regards,<br>
				Hector Beverages
				<br><br><p style="color:#424242;font-size:12px">In connection with your association with the company as a customer, you may provide to the company, certain information with respect to entity identification details, registration numbers, PAN and/or GST numbers, bank account details, personal information including sensitive personal data or information (as such term is defined in the Information Technology Act, 2000 read with the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011) and the Aadhaar number (as such term is defined under the Aadhaar (Targeted Delivery of Financial and Other Subsidies, Benefits and Services) Act, 2016), as may be applicable (“Information”). Any Information, if shared by you with the company, will be shared by you having full legal capacity and authority to share such Information and such Information will be collected, processed, stored, handled, used, transferred, disclosed and/or retained, as may be required, in accordance with the company’s confidentiality obligations, privacy policy and subject to applicable law, for the purpose of administering your association with the company and based on the requirements of such association for onboarding, registration, billing, accounting, conducting background checks, in connection with business of the company and the company’s internal record keeping purposes. The company may either by itself, or through third party service providers, process any Information for relevant and limited purposes in connection with your association with the company, subject to applicable laws. You, having read and understood the aforesaid terms of collection, processing, handling, use, transfer and disclosure of Information, are requested to provide your express consent while sharing the Information with the company. You shall as and when there is any update to the Information shared with the company, seek access and update such Information which relates to you. Your sharing of the Information with the company shall certify that such Information provided by you to the company is true, accurate and complete, and you hereby agree to fully indemnify and keep indemnified the company, its management, employees and representatives for any claims, demands, losses, damages, actions and/or other liabilities, whether financial or otherwise, arising directly or indirectly from any reliance upon such Information.</p>""".format(self.name_of_new_distributor,asm_rsm_name[0][0])
				frappe.sendmail(subject="Customer Creation Rejected : {}".format(self.name_of_new_distributor), content=msg, recipients = '{}'.format(self.owner), sender="Notification@hectorbeverages.com")
				print("\n email sent \n")

			if self.workflow_state == 'Rejected by RSM':
				frappe.db.set_value("Secondary Customer Form", self.name, "rejected_by_rsm_time", frappe.utils.now())
				msg="""Hello,<br><br>
				Your request for Secondary customer creation for customer {} has been rejected by {}.<br><br>
				Kindly check reason for rejection in website apps.myhector.com<br><br><br>
				Regards,<br>
				Hector Beverages
				<br><br><p style="color:#424242;font-size:12px">In connection with your association with the company as a customer, you may provide to the company, certain information with respect to entity identification details, registration numbers, PAN and/or GST numbers, bank account details, personal information including sensitive personal data or information (as such term is defined in the Information Technology Act, 2000 read with the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011) and the Aadhaar number (as such term is defined under the Aadhaar (Targeted Delivery of Financial and Other Subsidies, Benefits and Services) Act, 2016), as may be applicable (“Information”). Any Information, if shared by you with the company, will be shared by you having full legal capacity and authority to share such Information and such Information will be collected, processed, stored, handled, used, transferred, disclosed and/or retained, as may be required, in accordance with the company’s confidentiality obligations, privacy policy and subject to applicable law, for the purpose of administering your association with the company and based on the requirements of such association for onboarding, registration, billing, accounting, conducting background checks, in connection with business of the company and the company’s internal record keeping purposes. The company may either by itself, or through third party service providers, process any Information for relevant and limited purposes in connection with your association with the company, subject to applicable laws. You, having read and understood the aforesaid terms of collection, processing, handling, use, transfer and disclosure of Information, are requested to provide your express consent while sharing the Information with the company. You shall as and when there is any update to the Information shared with the company, seek access and update such Information which relates to you. Your sharing of the Information with the company shall certify that such Information provided by you to the company is true, accurate and complete, and you hereby agree to fully indemnify and keep indemnified the company, its management, employees and representatives for any claims, demands, losses, damages, actions and/or other liabilities, whether financial or otherwise, arising directly or indirectly from any reliance upon such Information.</p>""".format(self.name_of_new_distributor,asm_rsm_name[0][1])
				frappe.sendmail(subject="Customer Creation Rejected : {}".format(self.name_of_new_distributor), content=msg, recipients = '{}'.format(self.owner), sender="Notification@hectorbeverages.com")
				print("\n email sent \n")

			if self.workflow_state == 'Secondary Customer Approved':
				frappe.db.set_value("Secondary Customer Form", self.name, "secondary_customer_master_approval_time", frappe.utils.now())
				msg="""Hello Team,<br><br>
				Your request for Secondary customer creation has been approved. And New Customer Code is {} for {}.<br><br>
				Link- apps.myhector.com<br><br><br>
				Regards,<br>
				Hector Beverages
				<br><br><p style="color:#424242;font-size:12px">In connection with your association with the company as a customer, you may provide to the company, certain information with respect to entity identification details, registration numbers, PAN and/or GST numbers, bank account details, personal information including sensitive personal data or information (as such term is defined in the Information Technology Act, 2000 read with the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011) and the Aadhaar number (as such term is defined under the Aadhaar (Targeted Delivery of Financial and Other Subsidies, Benefits and Services) Act, 2016), as may be applicable (“Information”). Any Information, if shared by you with the company, will be shared by you having full legal capacity and authority to share such Information and such Information will be collected, processed, stored, handled, used, transferred, disclosed and/or retained, as may be required, in accordance with the company’s confidentiality obligations, privacy policy and subject to applicable law, for the purpose of administering your association with the company and based on the requirements of such association for onboarding, registration, billing, accounting, conducting background checks, in connection with business of the company and the company’s internal record keeping purposes. The company may either by itself, or through third party service providers, process any Information for relevant and limited purposes in connection with your association with the company, subject to applicable laws. You, having read and understood the aforesaid terms of collection, processing, handling, use, transfer and disclosure of Information, are requested to provide your express consent while sharing the Information with the company. You shall as and when there is any update to the Information shared with the company, seek access and update such Information which relates to you. Your sharing of the Information with the company shall certify that such Information provided by you to the company is true, accurate and complete, and you hereby agree to fully indemnify and keep indemnified the company, its management, employees and representatives for any claims, demands, losses, damages, actions and/or other liabilities, whether financial or otherwise, arising directly or indirectly from any reliance upon such Information.</p>""".format(self.super_stockist_code,self.name_of_new_distributor)
				frappe.sendmail(subject="Customer Creation Completed : {} : {}".format(self.super_stockist_code,self.name_of_new_distributor), content=msg, recipients = '{},{}'.format(asm_rsm[0][0], nsm_user[0][0]), sender="Notification@hectorbeverages.com")
				print("\n email sent \n")

			if self.workflow_state == 'Pending for RTM Approval':
				frappe.db.set_value("Secondary Customer Form", self.name, "nsm_approval_time", frappe.utils.now())
				for i in range(len(rtm_list)):
					msg="""Hello {},<br><br>
					You have received a request for Secondary customer creation approval from {} for the customer {}.<br><br>
					Kindly login to apps.myhector.com for the approval process.<br><br><br>
					Regards,<br>
					Hector Beverages
					<br><br><p style="color:#424242;font-size:12px">In connection with your association with the company as a customer, you may provide to the company, certain information with respect to entity identification details, registration numbers, PAN and/or GST numbers, bank account details, personal information including sensitive personal data or information (as such term is defined in the Information Technology Act, 2000 read with the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011) and the Aadhaar number (as such term is defined under the Aadhaar (Targeted Delivery of Financial and Other Subsidies, Benefits and Services) Act, 2016), as may be applicable (“Information”). Any Information, if shared by you with the company, will be shared by you having full legal capacity and authority to share such Information and such Information will be collected, processed, stored, handled, used, transferred, disclosed and/or retained, as may be required, in accordance with the company’s confidentiality obligations, privacy policy and subject to applicable law, for the purpose of administering your association with the company and based on the requirements of such association for onboarding, registration, billing, accounting, conducting background checks, in connection with business of the company and the company’s internal record keeping purposes. The company may either by itself, or through third party service providers, process any Information for relevant and limited purposes in connection with your association with the company, subject to applicable laws. You, having read and understood the aforesaid terms of collection, processing, handling, use, transfer and disclosure of Information, are requested to provide your express consent while sharing the Information with the company. You shall as and when there is any update to the Information shared with the company, seek access and update such Information which relates to you. Your sharing of the Information with the company shall certify that such Information provided by you to the company is true, accurate and complete, and you hereby agree to fully indemnify and keep indemnified the company, its management, employees and representatives for any claims, demands, losses, damages, actions and/or other liabilities, whether financial or otherwise, arising directly or indirectly from any reliance upon such Information.</p>""".format(frappe.get_doc('User', rtm_list[i]).full_name,nsm_name[0][0],self.name_of_new_distributor)
					frappe.sendmail(subject="Customer Creation: Pending with RTM Manager", content=msg, recipients = '{}'.format(rtm_list[i]),sender="Notification@hectorbeverages.com")
					print("\n email sent \n")

			if self.workflow_state == 'Rejected by RTM':
				frappe.db.set_value("Secondary Customer Form", self.name, "rejected_by_rtm_time", frappe.utils.now())
				msg="""Hello {},<br><br>
				Your request for Secondary customer creation for customer {} has been rejected by RTM Manager.<br><br>
				Kindly check reason for rejection in website apps.myhector.com<br><br><br>
				Regards,<br>
				Hector Beverages
				<br><br><p style="color:#424242;font-size:12px">In connection with your association with the company as a customer, you may provide to the company, certain information with respect to entity identification details, registration numbers, PAN and/or GST numbers, bank account details, personal information including sensitive personal data or information (as such term is defined in the Information Technology Act, 2000 read with the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011) and the Aadhaar number (as such term is defined under the Aadhaar (Targeted Delivery of Financial and Other Subsidies, Benefits and Services) Act, 2016), as may be applicable (“Information”). Any Information, if shared by you with the company, will be shared by you having full legal capacity and authority to share such Information and such Information will be collected, processed, stored, handled, used, transferred, disclosed and/or retained, as may be required, in accordance with the company’s confidentiality obligations, privacy policy and subject to applicable law, for the purpose of administering your association with the company and based on the requirements of such association for onboarding, registration, billing, accounting, conducting background checks, in connection with business of the company and the company’s internal record keeping purposes. The company may either by itself, or through third party service providers, process any Information for relevant and limited purposes in connection with your association with the company, subject to applicable laws. You, having read and understood the aforesaid terms of collection, processing, handling, use, transfer and disclosure of Information, are requested to provide your express consent while sharing the Information with the company. You shall as and when there is any update to the Information shared with the company, seek access and update such Information which relates to you. Your sharing of the Information with the company shall certify that such Information provided by you to the company is true, accurate and complete, and you hereby agree to fully indemnify and keep indemnified the company, its management, employees and representatives for any claims, demands, losses, damages, actions and/or other liabilities, whether financial or otherwise, arising directly or indirectly from any reliance upon such Information.</p>""".format(asm_rsm_name[0][0],self.name_of_new_distributor)
				frappe.sendmail(subject="Customer Creation Rejected : {}".format(self.name_of_new_distributor), content=msg, recipients = '{}'.format(asm_rsm[0][0]), sender="Notification@hectorbeverages.com")
				print("\n email sent \n")

			if self.workflow_state == 'Requested for More Details by RTM':
				frappe.db.set_value("Secondary Customer Form", self.name, "requested_for_more_details_by_rtm_time", frappe.utils.now())
				msg="""Hello {},<br><br>
				You have received a request for more information in Secondary customer creation from RTM Manager for the customer {}.<br><br>
				Kindly login to apps.myhector.com for the approval process.<br><br><br>
				Regards,<br>
				Hector Beverages
				<br><br><p style="color:#424242;font-size:12px">In connection with your association with the company as a customer, you may provide to the company, certain information with respect to entity identification details, registration numbers, PAN and/or GST numbers, bank account details, personal information including sensitive personal data or information (as such term is defined in the Information Technology Act, 2000 read with the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011) and the Aadhaar number (as such term is defined under the Aadhaar (Targeted Delivery of Financial and Other Subsidies, Benefits and Services) Act, 2016), as may be applicable (“Information”). Any Information, if shared by you with the company, will be shared by you having full legal capacity and authority to share such Information and such Information will be collected, processed, stored, handled, used, transferred, disclosed and/or retained, as may be required, in accordance with the company’s confidentiality obligations, privacy policy and subject to applicable law, for the purpose of administering your association with the company and based on the requirements of such association for onboarding, registration, billing, accounting, conducting background checks, in connection with business of the company and the company’s internal record keeping purposes. The company may either by itself, or through third party service providers, process any Information for relevant and limited purposes in connection with your association with the company, subject to applicable laws. You, having read and understood the aforesaid terms of collection, processing, handling, use, transfer and disclosure of Information, are requested to provide your express consent while sharing the Information with the company. You shall as and when there is any update to the Information shared with the company, seek access and update such Information which relates to you. Your sharing of the Information with the company shall certify that such Information provided by you to the company is true, accurate and complete, and you hereby agree to fully indemnify and keep indemnified the company, its management, employees and representatives for any claims, demands, losses, damages, actions and/or other liabilities, whether financial or otherwise, arising directly or indirectly from any reliance upon such Information.</p>""".format(nsm_name[0][0],self.name_of_new_distributor)
				frappe.sendmail(subject="Customer Creation: Requested for More Details by RTM Manager", content=msg, recipients = '{}'.format(nsm_user[0][0]), sender="Notification@hectorbeverages.com")
				print("\n email sent \n")

			if self.workflow_state == 'Resent for RTM Approval':
				frappe.db.set_value("Secondary Customer Form", self.name, "resent_for_rtm_approval_time", frappe.utils.now())
				for i in range(len(rtm_list)):
					msg="""Hello {},<br><br>
					You have received a request for Secondary customer creation approval from {} for the customer {}.<br><br>
					Kindly login to apps.myhector.com for the approval process.<br><br><br>
					Regards,<br>
					Hector Beverages
					<br><br><p style="color:#424242;font-size:12px">In connection with your association with the company as a customer, you may provide to the company, certain information with respect to entity identification details, registration numbers, PAN and/or GST numbers, bank account details, personal information including sensitive personal data or information (as such term is defined in the Information Technology Act, 2000 read with the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011) and the Aadhaar number (as such term is defined under the Aadhaar (Targeted Delivery of Financial and Other Subsidies, Benefits and Services) Act, 2016), as may be applicable (“Information”). Any Information, if shared by you with the company, will be shared by you having full legal capacity and authority to share such Information and such Information will be collected, processed, stored, handled, used, transferred, disclosed and/or retained, as may be required, in accordance with the company’s confidentiality obligations, privacy policy and subject to applicable law, for the purpose of administering your association with the company and based on the requirements of such association for onboarding, registration, billing, accounting, conducting background checks, in connection with business of the company and the company’s internal record keeping purposes. The company may either by itself, or through third party service providers, process any Information for relevant and limited purposes in connection with your association with the company, subject to applicable laws. You, having read and understood the aforesaid terms of collection, processing, handling, use, transfer and disclosure of Information, are requested to provide your express consent while sharing the Information with the company. You shall as and when there is any update to the Information shared with the company, seek access and update such Information which relates to you. Your sharing of the Information with the company shall certify that such Information provided by you to the company is true, accurate and complete, and you hereby agree to fully indemnify and keep indemnified the company, its management, employees and representatives for any claims, demands, losses, damages, actions and/or other liabilities, whether financial or otherwise, arising directly or indirectly from any reliance upon such Information.</p>""".format(frappe.get_doc('User', rtm_list[i]).full_name,nsm_name[0][0],self.name_of_new_distributor)
					frappe.sendmail(subject="Customer Creation: Resent for RTM Manager Approval", content=msg, recipients = '{}'.format(rtm_list[i]), sender="Notification@hectorbeverages.com")
					print("\n email sent \n")

		except:
			frappe.throw("Please add ASM in Sales Hierarchy Mapping")
